version: "3.9"
services:
  blog_web_app:
    container_name: blog-web-app
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@test.com
      DJANGO_SUPERUSER_PASSWORD: 1234
    depends_on:
      postgres_db:
        condition: service_healthy
    entrypoint: [ "./entrypoint.sh" ]

  postgres_db:
    image: postgres:latest
    container_name: postgres-local-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
